### ISSUE TITLE
Implement the data connector service to read the temporary JSON query results document

### ISSUE THREAD

**Issue by camelspeed** [Project-Heimdall/heimdall-webapp#80]
Failed QA but the commit merged to master to keep us going.
The acceptance criteria is that we must be dealing with the JSON document that ES gives us not our old JSON Document that was identical to our API Project model.

**Comment by onetrickwolf** [comment]
Note that grabbing release count may be useless or unreliable. Would recommend maybe looking at release downloads in the future.

**Comment by onetrickwolf** [comment]
Creating multiple instances from a single instance via a local operation hook from a memory database does not seem very straightforward. It also seems fairly different and much more difficult than how we would actually do it with remote calls. Since the remote calls are basically done, I don't think there is much need to keep exploring this issue.
